version: 2
mergeable:
  # Pending issue https://github.com/mergeability/mergeable/issues/573
  - name: "Assign maintenance"
    when: pull_request.*, pull_request_review.*
    validate:
      - do: changeset
        must_include:
          regex:
            - ".github\\/"
            - "client-apps\\/nx\\.json"
            - "client-apps\\/workspace\\.json"
            - "tn-api\\/Dockerfile"
            - "tn-api\\/docker-compose\\.yml"
            - "tn-api\\/entrypoint\\.sh"
            - "tn-api\\/config\\.ru"
            - "tn-api\\/Procfile"
            - "tn-api\\/\\.tool-versions"
            - "tn-api\\/\\.ruby-version"
    pass:
      - do: comment
        payload:
          body: This is old. Is it still relevant? Don't see me!
