version: 2
mergeable:
  # Pending issue https://github.com/mergeability/mergeable/issues/573
  - name: "Assign maintenance"
    when: pull_request.*, pull_request_review.*
    validate: []
    pass:
      - do: comment
        payload:
          body: This is old. Is it still relevant?
